import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import { PageLoding } from '@/components/page-loading'


const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Radiant',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning >
        <head>
          <link rel="icon" href="/logo.svg" sizes="any" />
        </head>
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
          <ThemeProvider attribute='class' defaultTheme='dark' enableSystem={false} storageKey='radiant-theme'>
            <SocketProvider>
              <ModalProvider />
                <QueryProvider>
                  {children}
                  {/* <PageLoding /> */}
                </QueryProvider>
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
