const API_KEY = process.env.GOOGLE_API_KEY

interface ChatTranslationProps {
  text: string
  target: string
}

export async function UseTextTranslate({text, target}: ChatTranslationProps): Promise<string> {
  try {
    const response = await fetch(
      `https://translation.googleapis.com/language/translate/v2?key=${API_KEY}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          q: text,
          target: target,
        }),
      }
    );

    if (!response.ok) {
      throw new Error('Translation request failed');
    }

    const data = await response.json();
    return data.data.translations[0].translatedText;
  } catch (error) {
    console.error('Translation error:', error);
    return text
    
  }
}


export async function GetTranslationLanguages(): Promise<{ code: string; name: string }[]> {
    try {
      const response = await fetch(
        `https://translation.googleapis.com/language/translate/v2/languages?key=${API_KEY}`, {cache: "force-cache"}
      );
  
      if (!response.ok) {
        throw new Error('Request to get supported languages failed');
      }
  
      const data = await response.json();
      const supportedLanguages = data.data.languages
        .filter((language: { language: string }) => language.language in languageCodeToName)
        .map((language: { language: string }) => ({
          code: language.language,
          name: languageCodeToName[language.language],
        }));
  
      return supportedLanguages;
    } catch (error) {
      console.error('Error getting supported languages:', error);
      throw error;
    }
  }

//   const languageCodeToName: { [key: string]: string } = {
//     Afrikaans:	"af",
// Albanian:	"sq",
// Amharic:	"am",
// Arabic:	"ar",
// Armenian:	"hy",
// Assamese:	"as",
// Aymara:	"ay",
// Azerbaijani:	"az",
// Bambara:	"bm",
// Basque:	"eu",
// Belarusian:	"be",
// Bengali:	"bn",
// Bhojpuri:	"bho",
// Bosnian:	"bs",
// Bulgarian:	"bg",
// Catalan:	"ca",
// Cebuano:	"ceb",
// Chinese: "zh",
// Corsican:	"co",
// Croatian:	"hr",
// Czech:	"cs",
// Danish:	"da",
// Dhivehi:	"dv",
// Dogri:	"doi",
// Dutch:	"nl",
// English:	"en",
// Esperanto:	"eo",
// Estonian:	"et",
// Ewe:	"ee",
// Filipino: "fil",
// Finnish:	"fi",
// French:	"fr",
// Frisian:	"fy",
// Galician:	"gl",
// Georgian:	"ka",
// German:	"de",
// Greek:	"el",
// Guarani:	"gn",
// Gujarati:	"gu",
// Haitian:	"ht",
// Hausa:	"ha",
// Hawaiian:	"haw",
// Hebrew:	"he",
// Hindi:	"hi",
// Hmong:	"hmn",
// Hungarian:	"hu",
// Icelandic:	"is",
// Igbo:	"ig",
// Ilocano:	"ilo",
// Indonesian:	"id",
// Irish:	"ga",
// Italian:	"it",
// Japanese:	"ja",
// Javanese: "jv",
// Kannada:	"kn",
// Kazakh:	"kk",
// Khmer:	"km",
// Kinyarwanda:	"rw",
// Konkani:	"gom",
// Korean:	"ko",
// Krio:	"kri",
// Kurdish:	"ku",
// Kyrgyz:	"ky",
// Lao:	"lo",
// Latin:	"la",
// Latvian:	"lv",
// Lingala:	"ln",
// Lithuanian:	"lt",
// Luganda:	"lg",
// Luxembourgish:	"lb",
// Macedonian:	"mk",
// Maithili:	"mai",
// Malagasy:	"mg",
// Malay:	"ms",
// Malayalam:	"ml",
// Maltese:	"mt",
// Maori:	"mi",
// Marathi:	"mr",
// Meiteilon: "mni-Mtei",
// Mizo:	"lus",
// Mongolian:	"mn",
// Myanmar:	"my",
// Nepali:	"ne",
// Norwegian:	"no",
// Nyanja:	"ny",
// Odia: "or",
// Oromo:	"om",
// Pashto:	"ps",
// Persian:	"fa",
// Polish:	"pl",
// Portuguese: "pt",
// Punjabi:	"pa",
// Quechua:	"qu",
// Romanian:	"ro",
// Russian:	"ru",
// Samoan:	"sm",
// Sanskrit:	"sa",
// Scots: "gd",
// Sepedi:	"nso",
// Serbian:	"sr",
// Sesotho:	"st",
// Shona:	"sn",
// Sindhi:	"sd",
// Sinhala:	"si",
// Slovak:	"sk",
// Slovenian:	"sl",
// Somali:	"so",
// Spanish:	"es",
// Sundanese:	"su",
// Swahili:	"sw",
// Swedish:	"sv",
// Tagalog:	"tl",
// Tajik:	"tg",
// Tamil:	"ta",
// Tatar:	"tt",
// Telugu:	"te",
// Thai:	"th",
// Tigrinya:	"ti",
// Tsonga:	"ts",
// Turkish:	"tr",
// Turkmen:	"tk",
// Twi:	"ak",
// Ukrainian:	"uk",
// Urdu:	"ur",
// Uyghur:	"ug",
// Uzbek:	"uz",
// Vietnamese:	"vi",
// Welsh:	"cy",
// Xhosa:	"xh",
// Yiddish:	"yi",
// Yoruba:	"yo",
// Zulu:	"zu",
//   };

  const languageCodeToName: { [key: string]: string } = {
    af: 'Afrikaans',
  sq: 'Albanian',
  am: 'Amharic',
  ar: 'Arabic',
  hy: 'Armenian',
  az: 'Azerbaijani',
  eu: 'Basque',
  be: 'Belarusian',
  bn: 'Bengali',
  bs: 'Bosnian',
  bg: 'Bulgarian',
  ca: 'Catalan',
  ceb: 'Cebuano',
  ny: 'Chichewa',
  zh: 'Chinese (Simplified)',
  zh_TW: 'Chinese (Traditional)',
  co: 'Corsican',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  nl: 'Dutch',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  tl: 'Filipino',
  fi: 'Finnish',
  fr: 'French',
  fy: 'Frisian',
  gl: 'Galician',
  ka: 'Georgian',
  de: 'German',
  el: 'Greek',
  gu: 'Gujarati',
  ht: 'Haitian Creole',
  ha: 'Hausa',
  haw: 'Hawaiian',
  iw: 'Hebrew',
  hi: 'Hindi',
  hmn: 'Hmong',
  hu: 'Hungarian',
  is: 'Icelandic',
  ig: 'Igbo',
  id: 'Indonesian',
  ga: 'Irish',
  it: 'Italian',
  ja: 'Japanese',
  jw: 'Javanese',
  kn: 'Kannada',
  kk: 'Kazakh',
  km: 'Khmer',
  ko: 'Korean',
  ku: 'Kurdish (Kurmanji)',
  ky: 'Kyrgyz',
  lo: 'Lao',
  la: 'Latin',
  lv: 'Latvian',
  lt: 'Lithuanian',
  lb: 'Luxembourgish',
  mk: 'Macedonian',
  mg: 'Malagasy',
  ms: 'Malay',
  ml: 'Malayalam',
  mt: 'Maltese',
  mi: 'Maori',
  mr: 'Marathi',
  mn: 'Mongolian',
  my: 'Myanmar (Burmese)',
  ne: 'Nepali',
  no: 'Norwegian',
  or: 'Odia (Oriya)',
  ps: 'Pashto',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  pa: 'Punjabi',
  ro: 'Romanian',
  ru: 'Russian',
  sm: 'Samoan',
  gd: 'Scots Gaelic',
  sr: 'Serbian',
  st: 'Sesotho',
  sn: 'Shona',
  sd: 'Sindhi',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  so: 'Somali',
  es: 'Spanish',
  su: 'Sundanese',
  sw: 'Swahili',
  sv: 'Swedish',
  tg: 'Tajik',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  ug: 'Uyghur',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  cy: 'Welsh',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zu: 'Zulu',
  };